title: Recycling / Trash Image Classifier
description: Classify recycling and trash images using deep learning
about:

  Edited to work with the TrashNet database by Aritro Saha.
  
  This is a Food Images Classifier using Deep Learning built on top of Pytorch and FastAI.


  The project was built originally by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)



code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: paper
    url: https://upload.wikimedia.org/wikipedia/commons/5/52/Continuous_form_paper_%2814p875_x_11%29.jpg
  - name: plastic
    url: https://4.imimg.com/data4/EU/YB/MY-6282801/normal-plastic-bottle-500x500.jpg
  - name: cardboard
    url: https://www.cargocabbie.ca/wp-content/uploads/2018/03/cargo-cabbie-shipping-box-12-x-12-x-9-500x500.jpg
  - name: metal
    url: https://images-na.ssl-images-amazon.com/images/I/61qwdONkmqL._SX466_.jpg
  - name: table (not in training)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
